
function mydialog
    d = dialog('Position',[300 300 350 150],'Name','Zoom the Image');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 80 310 40],...
               'String','Remember to zoom in on a medium brightness cell. Try to pick a cell on the periphery so you don''t have to zoom twice. Click the close button when you''re done.');

    btn = uicontrol('Parent',d,...
               'Position',[140 20 70 25],...
               'String','Close',...
               'Callback','delete(gcf)');
           pause
end